[tool.poetry]
name = "berserk"
version = "0.12.0-dev"
description = "Python client for the lichess API"
authors = ["Lichess <contact@lichess.org>"]
license = "GPL-3.0-or-later"
readme = "README.rst"
repository = "https://github.com/lichess-org/berserk"
keywords = ["lichess"]
classifiers = [
        'Development Status :: 4 - Beta',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
        'Natural Language :: English',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.8'
    ]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.28.2"
ndjson = "^0.3.1"
Deprecated = "^1.2.13"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "^7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
